version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: festimate-mysql-1
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
